=== landyking/link/link-core/src/main/resources/link/dict-1.0.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.github.com/landyking/link"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
    <xs:element name="dicts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="dict">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="item">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="xs:string"/>
                                    </xs:complexContent>
                                    <xs:attribute name="code" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== landyking/link/link-core/src/test/resources/link/dict/dt.xml
<?xml version="1.0" encoding="UTF-8"?>
<dicts xmlns="http://www.github.com/landyking/dict"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.github.com/landyking/dict http://www.github.com/landyking/dict/dict-1.0.xsd">
    <dict name="hello" desc="测试">
        <item code="2">你好</item>
        <item code="21">我也好</item>
        <item code="22">我也好2</item>
    </dict>
    <dict name="world">
        <item code="a">大写A</item>
        <item code="b">大写B</item>
    </dict>
    <dict name="app.marker">
        <item code="1" marker="first">第一</item>
        <item code="2" marker="second">第二</item>
    </dict>
</dicts>
