=== landyking/link/link-core/src/main/resources/link-1.0.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.github.com/landyking/link"
           xmlns="http://www.github.com/landyking/link"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">


    <xs:element name="directive">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description">
                    <xs:simpleType>
                        <xs:annotation>
                            <xs:documentation><![CDATA[描述信息]]></xs:documentation>
                        </xs:annotation>
                        <xs:restriction base="xs:string"/>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="input">
                    <xs:annotation>
                        <xs:documentation><![CDATA[]]></xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="param" type="paramType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="output">
                    <xs:annotation>
                        <xs:documentation><![CDATA[]]></xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="param" type="paramType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="execution">
                    <xs:complexType>
                        <xs:annotation>
                            <xs:documentation><![CDATA[指令实际执行内容，可以为一个操作序列]]></xs:documentation>
                        </xs:annotation>
                        <xs:sequence>
                            <xs:group ref="executionGroup" minOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dependencys">
                    <xs:annotation>
                        <xs:documentation><![CDATA[当前指令所依赖的其他指令，如果不填写，则无法进行内部指令调用]]></xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence minOccurs="0">
                            <xs:element name="dependency" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="paramType">
        <xs:sequence minOccurs="0">
            <xs:element name="processors">
                <xs:complexType>
                    <xs:sequence>
                        <xs:group ref="paramProcessorGroup"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation><![CDATA[]]></xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="desc" type="xs:string">
            <xs:annotation>
                <xs:documentation><![CDATA[]]></xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="notEmpty" type="xs:boolean" default="true">
            <xs:annotation>
                <xs:documentation><![CDATA[]]></xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="default" type="xs:string">
            <xs:annotation>
                <xs:documentation><![CDATA[]]></xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="fixed" type="xs:string">
            <xs:annotation>
                <xs:documentation><![CDATA[]]></xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:group name="paramProcessorGroup">
        <xs:choice>
            <xs:element name="ageCalc"/>
            <xs:element name="GUIDGenerator"/>
            <xs:element name="DateTimeGenerator"/>
            <xs:element name="AllToString"/>
            <xs:element name="DefaultValueGenerator"/>
            <xs:element name="QueryTranslator"/>
            <xs:element name="DictTranslator"/>
            <xs:element name="NotEmpty"/>
            <xs:element name="TextToList"/>
            <xs:element name="ListToText"/>
            <xs:element name="LikeParamGenerator"/>
            <xs:element name="InputScriptProcessor"/>
            <xs:element name="OutputScriptProcessor"/>
            <xs:element name="DateTimeConverter"/>
            <xs:element name="AgeCalc"/>
            <xs:element name="SqlLobProcessor"/>
            <xs:element name="JsonExpand"/>
        </xs:choice>
    </xs:group>
    <xs:group name="executionGroup">
        <xs:choice>
            <xs:element name="dbSql" type="xs:string"/>
            <xs:element name="dbDelete" type="xs:string"/>
            <xs:element name="dbInsert" type="xs:string"/>
            <xs:element name="dbQuery" type="xs:string"/>
            <xs:element name="dbUpdate" type="xs:string"/>
        </xs:choice>
    </xs:group>
</xs:schema>

=== landyking/link/link-core/src/main/resources/link/dv/hello/world.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description>测试指令</description>
    <input>
        <param name="name"/>
    </input>
    <execution>
        <dbSql></dbSql>
    </execution>
    <output>
        <param name="out" 3/>
    </output>
    <dependencys></dependencys>
</directive>

=== landyking/link/link-core/src/main/resources/link/dv/dbm/addDs.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description>新增数据源</description>
    <input>
        <param name="name" desc="名称">
            <processors>
                <Custom className="com.github.landyking.link.paramProcessor.custom.TestCustom">
                    <prop name="param2">hello 你好</prop>
                </Custom>
            </processors>
        </param>
        <param name="description" desc="描述"/>
        <param name="driverClass" desc="驱动类"/>
        <param name="jdbcUrl" desc="连接地址"/>
        <param name="account" desc="账号" notEmpty="false"/>
        <param name="password" desc="密码" notEmpty="false"/>
        <param name="extraConfig" desc="其他参数" notEmpty="false"/>
    </input>
    <execution>
        <custom className=""/>
    </execution>
    <output>
    </output>
    <dependencys></dependencys>
</directive>

=== landyking/link/link-core/src/main/resources/link/dv/dbm/listTableColumn.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description>列出数据库表中包含的列信息</description>
    <input>
        <param name="dsName" desc="数据源名称"/>
        <param name="catalog" desc="类别"/>
        <param name="schema" desc="格式"/>
        <param name="tableName" desc="表名"/>
    </input>
    <execution>
        <custom className=""/>
    </execution>
    <output>
        <param name="name" desc="字段名称"/>
        <param name="comment" desc="注释"/>
        <param name="type" desc="类型"/>
        <param name="size" desc="大小"/>
        <param name="precision" desc="精度"/>
        <param name="nullable" default="可否为空"/>
        <param name="primaryKey" desc="是否主键"/>
    </output>
    <dependencys></dependencys>
</directive>

=== landyking/link/link-core/src/test/resources/link/dv/emp/complexOutputList.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description>QueryTranslatorTest</description>
    <input>
        <param name="name" default="刘二"/>
        <param name="age" default="22"/>
        <param name="address" default="东大街18号"/>
        <param name="hello" default="world">
            <processors>
                <TextToList/>
            </processors>
        </param>
    </input>
    <execution>
        <custom id="default" className="com.github.landyking.link.execution.custom.InputGotoOutput"/>
    </execution>
    <executionEnding/>
    <output>
        <list name="root">
            <param name="name" from="#"/>
            <param name="age" from="#"/>
            <param name="address" from="[exec][default].data.![#this[address]]"/>
            <param name="hello" from="#"/>
            <param name="hello2" from="[exec][default].data.![#this[hello]][0]"/>
        </list>
    </output>
    <resultRender/>
    <dependencys></dependencys>
</directive>

=== landyking/link/link-core/src/main/resources/link/dv/dbm/listTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description>列出数据库表</description>
    <input>
        <param name="dsName" desc="数据源名称"/>
        <param name="catalog" desc="类别"/>
        <param name="schema" desc="格式"/>
    </input>
    <execution>
        <custom className=""/>
    </execution>
    <output>
        <param name="tableName"/>
        <param name="tableComment"/>
    </output>
    <dependencys></dependencys>
</directive>

=== landyking/link/link-core/src/main/resources/link/dv/dbInsert.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <input>
        <param name="" desc="" notEmpty="false" default="" fixed="">
            <processors>
            </processors>
        </param>
    </input>

    <execution>
        <dbInsert>
            <field ignoreNull="false" from="" column=""></field>
            <model></model>
        </dbInsert>
    </execution>
    <dependencys>
        <dependency></dependency>
    </dependencys>
    <output>
        <param name="count" from="num"/>
    </output>
</directive>

=== landyking/link/link-core/src/test/resources/link/dv/test/execution/dbSql.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description>自定义sql</description>
    <input>
        <param name="queryNo"/>
        <param name="deptNo"/>
        <param name="deptName"/>
    </input>
    <execution>
        <dbSql id="queryPage" dataSource="dataSource" pagination="true" limitDefaultSize="11">
            select dept_no from departments
        </dbSql>
        <dbSql id="queryOne" dataSource="dataSource" pagination="false">
            select dept_no from departments where dept_no = :queryNo
        </dbSql>
        <dbSql id="insertOne" dataSource="dataSource" pagination="false">
            insert into departments (dept_no,dept_name) values (:deptNo,:deptName)
        </dbSql>
        <dbSql id="deleteOne" dataSource="dataSource" pagination="false">
            delete departments where dept_no = :deptNo
        </dbSql>
    </execution>
    <executionEnding/>
    <output>
        <map name="root">
            <param name="success" from="true"/>
        </map>
    </output>
    <resultRender/>
    <dependencys></dependencys>
</directive>

=== landyking/link/link-core/src/main/resources/link/dv/dbm/listStruct.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description>列出数据库结构</description>
    <input>
        <param name="dsName" desc="数据源名称"/>
    </input>
    <execution>
        <custom className=""/>
    </execution>
    <output>
        <param name="catalog"/>
        <param name="schema"/>
    </output>
    <dependencys></dependencys>
</directive>
