=== landyking/link/link-core/src/main/resources/link-1.0.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.github.com/landyking/link"
           xmlns="http://www.github.com/landyking/link"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">


    <xs:element name="directive">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description">
                    <xs:simpleType>
                        <xs:annotation>
                            <xs:documentation><![CDATA[描述信息]]></xs:documentation>
                        </xs:annotation>
                        <xs:restriction base="xs:string"/>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="input">
                    <xs:annotation>
                        <xs:documentation><![CDATA[]]></xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="param" type="paramType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="output">
                    <xs:annotation>
                        <xs:documentation><![CDATA[]]></xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="param" type="paramType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="execution">
                    <xs:complexType>
                        <xs:annotation>
                            <xs:documentation><![CDATA[指令实际执行内容，可以为一个操作序列]]></xs:documentation>
                        </xs:annotation>
                        <xs:sequence>
                            <xs:group ref="executionGroup" minOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dependencys">
                    <xs:annotation>
                        <xs:documentation><![CDATA[当前指令所依赖的其他指令，如果不填写，则无法进行内部指令调用]]></xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence minOccurs="0">
                            <xs:element name="dependency" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="paramType">
        <xs:sequence minOccurs="0">
            <xs:element name="processors">
                <xs:complexType>
                    <xs:sequence>
                        <xs:group ref="paramProcessorGroup"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation><![CDATA[]]></xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="desc" type="xs:string">
            <xs:annotation>
                <xs:documentation><![CDATA[]]></xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="notEmpty" type="xs:boolean" default="true">
            <xs:annotation>
                <xs:documentation><![CDATA[]]></xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="default" type="xs:string">
            <xs:annotation>
                <xs:documentation><![CDATA[]]></xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="fixed" type="xs:string">
            <xs:annotation>
                <xs:documentation><![CDATA[]]></xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:group name="paramProcessorGroup">
        <xs:choice>
            <xs:element name="ageCalc"/>
            <xs:element name="GUIDGenerator"/>
            <xs:element name="DateTimeGenerator"/>
            <xs:element name="AllToString"/>
            <xs:element name="DefaultValueGenerator"/>
            <xs:element name="QueryTranslator"/>
            <xs:element name="DictTranslator"/>
            <xs:element name="NotEmpty"/>
            <xs:element name="TextToList"/>
            <xs:element name="ListToText"/>
            <xs:element name="LikeParamGenerator"/>
            <xs:element name="InputScriptProcessor"/>
            <xs:element name="OutputScriptProcessor"/>
            <xs:element name="DateTimeConverter"/>
            <xs:element name="AgeCalc"/>
            <xs:element name="SqlLobProcessor"/>
            <xs:element name="JsonExpand"/>
        </xs:choice>
    </xs:group>
    <xs:group name="executionGroup">
        <xs:choice>
            <xs:element name="dbSql" type="xs:string"/>
            <xs:element name="dbDelete" type="xs:string"/>
            <xs:element name="dbInsert" type="xs:string"/>
            <xs:element name="dbQuery" type="xs:string"/>
            <xs:element name="dbUpdate" type="xs:string"/>
        </xs:choice>
    </xs:group>
</xs:schema>

=== landyking/link/link-core/src/test/resources/link/dv/test/output/complexOutputList.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description>QueryTranslatorTest</description>
    <input>
        <param name="name"/>
        <param name="age"/>
        <param name="address"/>
        <param name="hello">
            <processors>
                <TextToList/>
            </processors>
        </param>
    </input>
    <execution>
        <custom id="default" className="com.github.landyking.link.execution.custom.InputGotoOutput"/>
    </execution>
    <executionEnding/>
    <output>
        <list name="root">
            <param name="name" />
            <param name="age" />
            <param name="address" from="[exec][default].data.![#this[address]]"/>
            <param name="hello" />
            <param name="hello2" from="[exec][default].data.![#this[hello]]"/>
        </list>
    </output>
    <resultRender/>
    <dependencys></dependencys>
</directive>

=== landyking/link/link-core/src/test/resources/link/dv/test/param/LikeParamGenerator.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description>dict check test</description>
    <input>
        <param name="like">
        </param>
        <param name="like2"/>
        <param name="likeEmpty" notEmpty="false">
        </param>
        <param name="likeLeft">
        </param>
        <param name="likeRight">
        </param>
        <param name="likeBoth">
        </param>
    </input>
    <execution>
        <custom id="default" className="com.github.landyking.link.execution.custom.InputGotoOutput"/>
    </execution>
    <executionEnding/>
    <output>
        <map name="root">
            <param name="like" />
            <param name="likeEmpty" />
            <param name="likeBoth" />
            <param name="likeBoth2" from="#contact('%',#root[input][like2],'%')"/>
            <param name="likeRight" />
            <param name="likeRight2" from="#contact(#root[input][like2],'%')"/>
            <param name="likeLeft" />
            <param name="likeLeft2" from="#contact('%',#root[input][like2])"/>
        </map>
    </output>
    <resultRender/>
    <dependencys></dependencys>
</directive>

=== landyking/link/link-core/src/test/resources/link/dv/emp/qtTest1.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description>QueryTranslatorTest</description>
    <input>
        <param name="deptName">
            <processors>
                <QueryTranslator queryDataSource="emp" table="departments"
                                 destField="dept_no" displayField="dept_name">
                    <!--<where>dept_name not in('Production')</where>-->
                </QueryTranslator>
            </processors>
        </param>
        <param name="ld" default="223" desc="本地字典翻译测试"/>
    </input>
    <execution>
        <custom id="default" className="com.github.landyking.link.execution.custom.InputGotoOutput"/>
    </execution>
    <executionEnding/>
    <output>
        <param name="deptName"/>
        <param name="ld">
            <processors>
                <DictTranslator dict="hello"/>
            </processors>
        </param>
    </output>
    <resultRender/>
    <dependencys></dependencys>
</directive>

=== landyking/link/link-core/src/main/resources/link/dv/dbDelete.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description></description>
    <input>
        <param name="33"/>
        <param name="3"/>
        <param name="test"/>
    </input>
    <execution transaction="false">
        <dbDelete>
            <table>
                t_test
            </table>
            <where>
                hello = :test and address in (:lala)
            </where>
        </dbDelete>
    </execution>
    <output>
        <param name="1" from=""/>
        <param name="12" from=""/>
        <param name="123" from=""/>
    </output>
    <dependencys>
    </dependencys>
</directive>

=== landyking/link/link-core/src/main/resources/link/dv/dbm/executeSql.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description>执行SQL语句</description>
    <input>
        <param name="dsName" desc="数据源名称"/>
        <param name="sql" desc="SQL语句"/>
        <param name="page" desc="页码"/>
        <param name="limit" desc="页长"/>
    </input>
    <execution>
        <custom className=""/>
    </execution>
    <output custom="true">
    </output>
    <dependencys></dependencys>
</directive>

=== landyking/link/link-core/src/main/resources/link/dv/dbm/listDs.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description>列出数据源</description>
    <input>
        <param name="page" default="1"/>
        <param name="limit" default="10"/>
    </input>
    <execution>
        <custom className=""/>
    </execution>
    <output>
        <param name="name" desc="名称"/>
        <param name="description" desc="描述"/>
        <param name="driverClass" desc="驱动类"/>
        <param name="jdbcUrl" desc="连接地址"/>
        <param name="account" desc="账号"/>
        <param name="password" desc="密码"/>
        <param name="extraConfig" desc="其他参数"/>
    </output>
    <dependencys></dependencys>
</directive>

=== landyking/link/link-core/src/main/resources/link/dv/emp/deleteEmployee.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description>新增雇员信息</description>
    <input>
        <param name="firstName" desc="名">
            <processors>
                <TextToList/>
            </processors>
        </param>
    </input>
    <execution>
        <dbDelete id="default" dataSource="emp">
            <table>employees</table>
            <where>first_name in (:firstName)</where>
        </dbDelete>
    </execution>
    <output>
    </output>
    <dependencys></dependencys>
</directive>

=== landyking/link/link-core/src/main/resources/link/dv/dbSql.xml
<?xml version="1.0" encoding="UTF-8"?>
<directive xmlns="http://www.github.com/landyking/link"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.github.com/landyking/link http://www.github.com/landyking/link/link-1.0.xsd">
    <description><![CDATA[师曾发生]]></description>
    <input>
        <param name="" desc="" notEmpty="true" default="" fixed="">
            <processors>
                <ageCalc></ageCalc>
            </processors>
        </param>
    </input>
    <output>
        <param name=""/>
    </output>
    <execution>
        <dbDelete>22</dbDelete>
        <dbUpdate>22</dbUpdate>
        <dbSql>sdfasdf</dbSql>
        <dbInsert>22</dbInsert>
        <dbInsert>22</dbInsert>
        <dbSql>22</dbSql>
    </execution>
    <dependencys></dependencys>
</directive>
